### ISSUE TITLE
Add edge-to-visual-only tokens

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-tokens#28]
We should publish `edge-to-visual-only` tokens for use when there is only a visual within a component and no text. Currently, specs assume horizontal centering, but this data is necessary for some implementations (i.e. CSS subtracts these values from the text-only padding to get the icon-only padding, as text-only is default):

```
.spectrum--medium {
  /* edge-to-visual-only is used for icon-only buttons */
  --spectrum-edge-to-visual-only-75: 4px;
  --spectrum-edge-to-visual-only-100: 7px;
  --spectrum-edge-to-visual-only-200: 10px;
  --spectrum-edge-to-visual-only-300: 13px;
}

.spectrum--large {
  /* edge-to-visual-only is used for icon-only buttons */
  --spectrum-edge-to-visual-only-75: 5px;
  --spectrum-edge-to-visual-only-100: 9px;
  --spectrum-edge-to-visual-only-200: 13px;
  --spectrum-edge-to-visual-only-300: 16px;
}
```

**Comment by GarthDB** [comment]
https://github.com/adobe/spectrum-tokens/blob/3ff8fd5181648b24c61368b5d5f0ce7744a5b890/packages/tokens/src/layout.json#L833-L907
