### ISSUE TITLE
Config rename not reflected in package.json

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-tokens#89]
https://github.com/adobe/spectrum-tokens/blob/4250036a7923837a2e28937812b2488c40f29b61/package.json#L6

It looks like the `config.js` file was renamed but the package.json was not updated to reflect the change. This means that `require.resolve` is not able to find the asset in question.

Not a blocking issue; I was able to work around the issue by updating from `require.resolve("@adobe/spectrum-tokens")` to `require.resolve("@adobe/spectrum-tokens/package.json")`.

**Comment by GarthDB** [comment]
It's been updated and points to the `tasks/buildSpectrumTokens.js` file.
