### ISSUE TITLE
Typing and/or schema validation

### ISSUE THREAD

**Issue by castastrophe** [adobe/spectrum-tokens#99]
Is there a way to include typing information in the token json?

[Internal Slack link](https://adobedesign.slack.com/archives/C0B4TK7E2/p1679419201125589)

In this example, a variable was updated from `--spectrum-font-weight-black: 900;` to `--spectrum-font-weight-black: black;` which ended up being an invalid type when applied to the CSS `font-weight` property.  Since that particular property was not in use, there was no way for to validate if it was going to work in CSS or not (it's a valid custom property after all, pretty much everything is). Perhaps there's a way to include typing information so we can filter/highlight potential issues automatically in future?

**Comment by GarthDB** [comment]
Typing has been added in https://github.com/adobe/spectrum-tokens/releases/tag/@adobe/spectrum-tokens@12.23.0. changes can be found in https://github.com/adobe/spectrum-tokens/commit/4fc4a5005b782e3f10182b2b198d7e90859985fe.
